### ISSUE TITLE
ImportError: cannot import name whitelist

### ISSUE THREAD

**Issue by mguesdon** [nbs-system/nxtool-ng#14]
Hi,

 I've copied naxsi-0.55.1/nxapi/nxapi into /usr/lib/python2.7/site-packages/ but when doing "python nxtool.py -h", I get:
<<
Traceback (most recent call last):
  File "nxtool.py", line 5, in <module>
    from nxapi import whitelist as nxapi_whitelist
ImportError: cannot import name whitelist
>>

Where can I get this "whitelist" ?

Thx !

**Comment by mguesdon** [comment]
Sorry, stupid question: I've found https://github.com/nbs-system/nxapi/

**Comment by jvoisin** [comment]
```python
pip -r ./dependencies.txt
```

;)

**Comment by mguesdon** [comment]
Thx ! 
Yes, it will help python beginners like me :-)
