### ISSUE TITLE
No search type for [count]

### ISSUE THREAD

**Issue by atomspring** [nbs-system/nxtool-ng#24]
Hello again, I try running `python nxtool.py --stats --elastic` and the command fails with

> elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'No search type for [count]')

This works using the original nxtool, elasticsearch is 5.3.0 on a ubuntu 16.04 system.

**Comment by sabban** [comment]
Should be fixed in last commit.
Thanks for reporting this bug.
